require: rubocop-rails
AllCops:
  Exclude:
    - db/**/*.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - node_modules/**/*
    - bin/*
Style/HashSyntax:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
    Exclude:
    - spec/**/*.rb
Metrics/ModuleLength:
    Exclude:
    - spec/**/*.rb
Style/ExpandPathArguments:
    Exclude:
    - bin/rails
Metrics/AbcSize:
  Max: 15.52

