version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers-legacy
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6.5
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: great-reads-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: yarn install
          command: yarn

      # Store bundle cache
      - save_cache:
          key: great-reads-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Create database
          command: bundle exec rake db:create
      - run:
          name: Load database schema
          command: bundle exec rake db:schema:load

      # Tests
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Jest
          command: yarn test --maxWorkers=2

      - run:
          name: Node coverage
          command: yarn coverage

      # Save Coverage Analysis
      - store_artifacts:
          path: coverage
          destination: coverage
