export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const TOGGLE_HEADER_DROPDOWN = "TOGGLE_HEADER_DROPDOWN";
export const SET_ACTIVE_NAV_ITEM = "SET_ACTIVE_NAV_ITEM";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const SET_MODAL_TYPE = "SET_MODAL_TYPE";
